package com.liuc.server.api.bean.app;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.File;
import java.util.Date;

@Data
@ApiModel
public class CommonFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.fid
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fidfileId")
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.upload_type
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="uploadType上传类型 1:头像；2；附件;3:公开文件")
    private Integer uploadType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.file_name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fileName文件名")
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.file_type
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fileType文件类型")
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.file_size
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fileSize文件大小")
    private Double fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.img_url
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="imgUrl文件路径")
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.file_md5
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fileMd5文件指纹")
    private String fileMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.file_url
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fileUrl文件url")
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="createTime创建时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_file.is_delete
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="isDelete是否删除 1:是;0:否")
    private Integer isDelete;

    private File file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.fid
     *
     * @return the value of common_file.fid
     *
     * @mbg.generated
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.fid
     *
     * @param fid the value for common_file.fid
     *
     * @mbg.generated
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.upload_type
     *
     * @return the value of common_file.upload_type
     *
     * @mbg.generated
     */
    public Integer getUploadType() {
        return uploadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.upload_type
     *
     * @param uploadType the value for common_file.upload_type
     *
     * @mbg.generated
     */
    public void setUploadType(Integer uploadType) {
        this.uploadType = uploadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.file_name
     *
     * @return the value of common_file.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.file_name
     *
     * @param fileName the value for common_file.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.file_type
     *
     * @return the value of common_file.file_type
     *
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.file_type
     *
     * @param fileType the value for common_file.file_type
     *
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.file_size
     *
     * @return the value of common_file.file_size
     *
     * @mbg.generated
     */
    public Double getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.file_size
     *
     * @param fileSize the value for common_file.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.img_url
     *
     * @return the value of common_file.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.img_url
     *
     * @param imgUrl the value for common_file.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.file_md5
     *
     * @return the value of common_file.file_md5
     *
     * @mbg.generated
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.file_md5
     *
     * @param fileMd5 the value for common_file.file_md5
     *
     * @mbg.generated
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.file_url
     *
     * @return the value of common_file.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.file_url
     *
     * @param fileUrl the value for common_file.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.create_time
     *
     * @return the value of common_file.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.create_time
     *
     * @param createTime the value for common_file.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_file.is_delete
     *
     * @return the value of common_file.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_file.is_delete
     *
     * @param isDelete the value for common_file.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}