package com.liuc.server.api.common;


import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

public interface CommonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated
     */
    @Select(" ${sql} ")
    @Results({
    })
    List<Map<String,Object>> commonSelect(Map sql);


    @Insert(" ${sql} ")
    @Results({
    })
    int commonInsert(Map sql);

    @Update(" ${sql} ")
    @Results({
    })
    int commonUpdate(Map sql);

    @Delete(" ${sql} ")
    @Results({
    })
    int commonDel(Map sql);

}